name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set Configuration
        run: echo ${{ secrets.FIREBASE_CONFIG }} > firebase.json

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "getneil-goldilocks"
          entrypoint: "./main.ts" # TODO: update entrypoint